### ISSUE TITLE
xubuntu 14.04 baterry icon missing

### ISSUE THREAD

**Issue by ghost** [NitruxSA/nitrux-icons#16]
after I upgraded to Xubuntu 4.14, the icon of charged battery no longer appears only when the battery is discharging.

charged
![battery-charged](https://cloud.githubusercontent.com/assets/434850/2742922/9fe37cde-c70b-11e3-84c4-b910f1a64723.png)

discharging
![battery discharging](https://cloud.githubusercontent.com/assets/434850/2742927/ade98e54-c70b-11e3-901e-1d709117af6b.png)

thanks

**Comment by UriHerrera** [comment]
Closed as there was no further activity.
