### ISSUE TITLE
Support new programs

### ISSUE THREAD

**Issue by hbertoldo** [NitruxSA/nitrux-icons#20]
Dear developers,

I would like to congratulate you for the work
and ask if can add support for these programs?

checkbox-gui 0.17.6;
conky-manager 1.2.0.1;
colord 1.0.6-1;
i-nex 0.6.4;
master-pdf-editor 1.9.25;
openoffice 4.1.0;
tagtool 0.12.3;
texmacs 1:1.0.7;
tv-maxe 0.09;
unity-control-center 14.04.3+;
xdiagnose 3.6.3;
xfig 1:3.2.5;
xterm 297-1;
winetricks 0.0.+20140302;

Prints:
1- http://goo.gl/pFaSp4
2- http://goo.gl/rWrSWk
3- http://goo.gl/8fHpLa
4- http://goo.gl/t0fTk0
5- http://goo.gl/awBd2l

Thank you! and sorry for my english.

**Comment by UriHerrera** [comment]
Closed as there was no further activity.
