### ISSUE TITLE
Missing icon for modo, Autodesk Maya

### ISSUE THREAD

**Issue by hkenneth** [NitruxSA/nitrux-icons#25]
modo 701/801: http://www.thefoundry.co.uk/products/modo/latest-version/
Autodesk Maya: http://www.autodesk.com/products/autodesk-maya/overview

I feel like Nitrux does not have icons for most commercial applications from Autodesk and the Foundry.

**Comment by UriHerrera** [comment]
Closed as there was no further activity.
