### ISSUE TITLE
Missing icon for Plex Media Server

### ISSUE THREAD

**Issue by hkenneth** [NitruxSA/nitrux-icons#26]
I found there is icon for Plex Home Theater but the server icon is missing.

The .desktop file for PMS is:

[Desktop Entry]
Name=Plex Media Manager
GenericName=Media Manager
Comment=Manage your Plex Media
Exec=x-www-browser http://localhost:32400/manage
Icon=plexmediamanager
Terminal=false
Type=Application
Categories=AudioVideo;Audio;Music;Video;Player;Media;

Therefore need a link for plexmediamanager...

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.
