### ISSUE TITLE
Version: 3.4 - User status icons are not used by kde telepathy contacts

### ISSUE THREAD

**Issue by dzklaim** [NitruxSA/nitrux-icons#36]
system: arch linux x64
kde: 4.14.1
app: kde telepathy contacts

The user status icons are not detected. It seems that only the icons in the 22 folder are used.

![snapshot2](https://cloud.githubusercontent.com/assets/1281848/4473658/eb00aefe-4955-11e4-8233-16cd1074a7d4.png)

white envelope

![snap1](https://cloud.githubusercontent.com/assets/1281848/4484648/20084298-49be-11e4-9d19-4aac253c0042.png)

**Comment by UriHerrera** [comment]
Icon is present in the icon theme as of version 3.4.3.
