### ISSUE TITLE
Pithos Icon Request

### ISSUE THREAD

**Issue by rstreeter** [NitruxSA/nitrux-icons#38]
I was wondering if an icon for Pithos Pandora client please. The name from the desktop file is pithos and here is what the default icon is 
![screenshot](https://cloud.githubusercontent.com/assets/500779/4530673/fbc2acac-4d82-11e4-99ee-ade95845ed2f.png)

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.
