### ISSUE TITLE
XBMC = Kodi

### ISSUE THREAD

**Issue by ghost** [NitruxSA/nitrux-icons#40]
Can you change the icon or add a new icon for Kodi.
XBMC changed the name in Kodi.

**Comment by Superpiffer** [comment]
The migration to Kodi is complete, the new .desktop file is this:
[Desktop Entry]
Version=1.0
Name=Kodi Media Center
GenericName=Media Center
Comment=Manage and view your media
Exec=kodi
Icon=kodi
Terminal=false
Type=Application
Categories=AudioVideo;Video;Player;TV;

Actions=Fullscreen;Standalone;

[Desktop Action Fullscreen]
Name=Open in fullscreen
Exec=kodi -fs
OnlyShowIn=Unity;

[Desktop Action Standalone]
Name=Open in standalone mode
Exec=kodi --standalone
OnlyShowIn=Unity;

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.
