### ISSUE TITLE
OSes folder (FS UBuntu icons)

### ISSUE THREAD

**Issue by gusbemacbr** [NitruxSA/nitrux-icons#44]
Hello,

As you added the icons of Firestorm, Second and other, and released, and you asked me to add the OSes folders missing.

See the example of FS UBuntu icons that you should make:

![fs ubuntu folders](https://cloud.githubusercontent.com/assets/2257024/4947953/0ca70f7a-661c-11e4-81ca-1eb0a33fd60a.png)

Notice the folders of Windows, Apple and VMWare. 

I'll be sincere to you. I hate FontForge icon, sorry, can you make an alternative icon?

You should learn from these following icons:

![apps-fontforge-icon](https://cloud.githubusercontent.com/assets/2257024/4947970/86571892-661c-11e4-914f-30624102cc8a.png)
![flstudio_5971](https://cloud.githubusercontent.com/assets/2257024/4947991/21c6ae1e-661d-11e4-8273-1ebabb4576a3.png)

**Comment by UriHerrera** [comment]
Added these folders for 3.4.5.
