### ISSUE TITLE
Missing icon: opera-beta.

### ISSUE THREAD

**Issue by xandcg** [NitruxSA/nitrux-icons#46]
Dear Nitrux Team:

The icon for opera beta is missing. A symbolic link from opera-next-browser.svg seems OK to me.

Thank you!

![opera-beta](https://cloud.githubusercontent.com/assets/6910384/5058621/54b7c8e4-6cdf-11e4-98bb-a9ab762e498c.png)

[Desktop Entry]
Version=1.0
Name=Opera beta
GenericName=Web browser
Comment=Fast and secure web browser
TryExec=opera-beta
Exec=opera-beta %U
Terminal=false
Icon=opera-beta
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
Actions=NewWindow;NewPrivateWindow;

[Desktop Action NewWindow]
Name=New Window
Exec=opera-beta --new-window
X-TargetEnvironment=Unity

[Desktop Action NewPrivateWindow]
Name=New Private Window
Exec=opera-beta --private
X-TargetEnvironment=Unity

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.
