### ISSUE TITLE
Missing Icon: MusicBranz Picard

### ISSUE THREAD

**Issue by xandcg** [NitruxSA/nitrux-icons#47]
The icon for Picard, MusicBranz tagger is missing.

[Desktop Entry]
Name=MusicBrainz Picard
Comment=Tag your music with the next generation MusicBrainz tagger
Exec=picard %F
Terminal=false
Type=Application
StartupNotify=true
Icon=picard
Categories=AudioVideo;Audio;AudioVideoEditing;
MimeType=audio/x-mp3;audio/ogg;audio/mpeg;application/ogg;audio/x-flac;audio/x-flac+ogg;audio/x-vorbis+ogg;audio/x-speex+ogg;audio/x-oggflac;audio/x-musepack;audio/x-tta;audio/x-ms-wma;audio/x-wavpack;

Thank you!
![picard](https://cloud.githubusercontent.com/assets/6910384/5749330/273b7710-9c2f-11e4-9527-59ddb02f7110.png)

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.
