### ISSUE TITLE
Pan icon showing instead of arrow-down

### ISSUE THREAD

**Issue by aquatix** [NitruxSA/nitrux-icons#48]
I've got a weird issue while using Gnome 3.14 from the ppa's on Ubuntu 14.10. It's demonstrated by someone else at http://www.neowin.net/forum/topic/1232377-anyone-tried-gnome-314-on-ubuntu-1410-already/

Basically, I get a broken icon or pan/rss icon instead of the arrow-down in dropdown widgets and gnome-shell's system menu. All Nitrux' icon themes have this odd issue. Faba icons themes for example work fine.

If needed, I can provide some screenshots of my own setup.

Anyway, keep up the great job!

**Comment by UriHerrera** [comment]
I'll update my VM to 3.14. None of the icon theme shave an icon called *pan.svg* so it's probable that Gnome devs changed that icon to be provided by the icon theme rather than Gnome Shell itself.

**Comment by UriHerrera** [comment]
I've updated my VM. I've installed the icons manually to my home folder and had no issues, I've also installed them through the DEB package from our PPA and also had no issues. 

As you can see I'm using Nautilus 3.14.2, Gnome Shell 3.14.3 and Nitrux icons 3.4.3

![](http://i.imgur.com/DPh8q1F.png)

And this is with Compass 1.3.3, also installed from the DEB package.

![](http://i.imgur.com/3cBCjb0.png)

**Comment by aquatix** [comment]
Meh, I suspect something wonky with the packages in the 14.10 ppa. Most other themes also have a broken image or the rss-icon, but I think the pan.svg is a red herring. I installed 14.04 as Ubuntu Gnome, so no messing around with Unity or something.

I'll set up a VM to try to reproduce, but if 15.04 works fine... I guess it's just something special on my setup or upgrade path then, that only a few others have encountered. Sorry for the noise and keep up the great job!

**Comment by UriHerrera** [comment]
I just had the bug you described after some updates a few minutes ago. My cursor disappeared too,and the arrows were RSS icons and broken in tweak tool. I rebooted my VM and checked that I had nothing selected as *Cursor*. I then installed `adwaita-icon-theme-full` and rebooted again, selected the Nitrux icons and rebooted one more time. Now I have the correct icons again.

**Comment by aquatix** [comment]
I noticed after the comment by @UriHerrera that only `adwaita-icon-theme` was installed. After getting `adwaita-icon-theme-full`, the arrows and such work just fine. *facepalm*

Anyway, currently rocking the Compass theme :)
