### ISSUE TITLE
[LInux] SWTOR

### ISSUE THREAD

**Issue by ahjolinna** [NitruxSA/nitrux-icons#53]
could u make icon for Star Wars: The Old Republic, it's works only on wine/playonlinux

here is .desktop http://pastebin.com/KAk8s2gm (made by playonlinux)
here is the logo: http://www.eykerman.com/wp-content/uploads/2013/02/logo-both-factions.jpg

**Comment by UriHerrera** [comment]
Icon added to version 3.4.5.
