### ISSUE TITLE
Thumbnails for plain text files

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#54]
I use Nitrux under Ubuntu and the fact that I can't see thumbnails for plain text  files has been bothering me (a little bit) for some time as I can see them when I switch to default icon theme (Humanity or ubuntu-mono-light, etc.)
I've finally got down to it yesterday and solved this puzzle.
1) I opened the file "~/.local/share/icons/Nitrux/mimetypes/48/text-x-preview.svg" in Inkscape, and removed the dark grey layer in the main area so that the contents of plain text files to be displayed there as thumbnail images will be more visible.
2) I then copied the "text-x-preview.icon" (plain text) file from the corresponding location in the Humanity icon theme.
And that's it! I now have contents of plain text files displayed as thumbnails using the image "text-x-preview.svg" as a sort of canvas!
Also copying the other "text-x-preview.icon" files for sizes 22 and 24 in the Humanity icon theme ensured that I can have the contents of plain text files displayed as thumbnails in all sizes both below and above 48.
![screenshot from 2015-02-26 09 51 38](https://cloud.githubusercontent.com/assets/6375934/6388002/1bb205f0-bd9d-11e4-92c0-86f27536b49b.png)

**Comment by UriHerrera** [comment]
So it basically comes down to the background color of the icon?.

**Comment by Sadi58** [comment]
Yes, in addition to including a "text-x-preview.icon" file for mimetype icon sizes 48px and below I guess.

**Comment by UriHerrera** [comment]
Added to version 3.4.4 -update when the new version is available.

**Comment by Sadi58** [comment]
Unfortunately Nautilus also needs "text-x-preview.icon" files for mimetype icon sizes 48, 24 and 22 (as in the Humanity icon theme) to be able to display thumbnails for plain-text files.

**Comment by Sadi58** [comment]
UPDATE: Ubuntu 15.04 / Nautilus 3.14.x somehow doesn't care about "text-preview" any more ;-)
Adding such a text file named "text-x-preview.icon" in "mimetypes" sub-folder(s) of the icon theme now doesn't help to generate thumbnails for text files :-(

**Comment by UriHerrera** [comment]
Nautilus doesn't generate thumbnails for me either. Only for images.
