### ISSUE TITLE
Synaptic package status icons

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#55]
There used to be very nice Synaptic package status icons under a subfolder (./tools/synaptic), I wonder why you've decided to withdraw them.
Every time I update, I put them back from my archives and edit the index.theme file accordingly ;-)

**Comment by UriHerrera** [comment]
I've added back to version 3.4.5.

**Comment by Sadi58** [comment]
Thanks a lot for adding this beauty to synaptic :-)
