### ISSUE TITLE
[Linux] ClipIt tray icon Unity

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#56]
I use ClipIt (forked from parcellite) clipboard manager, which has a nice app icon in Nitrux, but in order to have a monochrome icon displayed in Unity top panel (systray) I need to
copy the svg version of the attached icon (clipit-trayicon.svg) to ./status/22
![clipit](https://cloud.githubusercontent.com/assets/6375934/6561199/0031e922-c698-11e4-8265-08faf77ffb72.png)
Perhaps you might consider incorporating this in the next version?
I can provide the svg file or perhaps you can come up with a better one...

**Comment by UriHerrera** [comment]
Added to version 3.5.3
