### ISSUE TITLE
[Linux] Redshift tray icon Unity

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#57]
I use Redshift for some automatic screen brightness/color/etc. adjustments, which has a nice app icon in Nitrux, but in order to have a monochrome icon displayed in Unity top panel (systray) I need to
copy the svg versions of the attached icons (redshift-status-on.svg and redshift-status-off.svg) to ./status/22
![redshift-status-on](https://cloud.githubusercontent.com/assets/6375934/6561531/ac1b13a6-c69a-11e4-96e7-a8aa68b9232a.png)
![redshift-status-off](https://cloud.githubusercontent.com/assets/6375934/6561534/af436c18-c69a-11e4-94aa-5c618aa2ead3.png)

Perhaps you might consider incorporating this in the next version?
I can provide the svg files or perhaps you can come up with better ones...

**Comment by UriHerrera** [comment]
Added to version 3.5.3
