### ISSUE TITLE
[Linux] VLC media player monochrome tray icon Unity

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#58]
I use VLC as my default media player, which has a nice app icon in Nitrux, but in order to have a monochrome icon displayed in Unity top panel (systray) instead of the small size app icon, I need to create a symlink like this:

ln -sf "./actions/22/media-playback-start.svg" "./status/22/vlc.svg"

Perhaps you might consider incorporating this in the next version?

**Comment by UriHerrera** [comment]
icon added to version 3.5.3
