### ISSUE TITLE
[Linux] Cantata using Oxygen icons KDE

### ISSUE THREAD

**Issue by xandcg** [NitruxSA/nitrux-icons#61]
Dear Uri Herrera,

Since last update for Nitrux KDE 3.5.0 some icons on cantata become falling back on oxygen icon theme.

Thanks!

![snapshot18](https://cloud.githubusercontent.com/assets/6910384/7032167/52d4a546-dd47-11e4-9754-49a1f09341a1.png)

**Comment by xandcg** [comment]
Update: the issue only happens when cantata is compiled with qt5 support instead of qt4 but doesn't happens when Nitrux was 3.4.4.

**Comment by UriHerrera** [comment]
It doesn't happen with Cantata Qt5 and 3.4.4?.

**Comment by xandcg** [comment]
No, started just after the 3.5.0 instalation. I opened the Cantata immediately after the instalation.
I would like to test it with 3.4.4 again but I do not have the source anymore.

Thanks!

**Comment by UriHerrera** [comment]
Are you using Arch, Antergos, Manjaro or anything else that uses an AUR or a similar repository? if so, the tars where mixed, I have re-uploaded them.

**Comment by xandcg** [comment]
No, I am on Gentoo here.

**Comment by UriHerrera** [comment]
Version 3.5.1 out, can you try with this one?.

**Comment by xandcg** [comment]
Using 3.5.1 and everything is fine again. :+1: 

Thanks!
