### ISSUE TITLE
Missing symbolic icons since 3.5 and more

### ISSUE THREAD

**Issue by solbjorn** [NitruxSA/nitrux-icons#62]
After updating to 3.5 many symbolic icons fall back to Adwaita theme or color variants on Cinnamon 2.4.8.
![1](https://cloud.githubusercontent.com/assets/12006295/7215193/30d17e7a-e5d4-11e4-98d9-e69027fbf049.png)
![2](https://cloud.githubusercontent.com/assets/12006295/7215191/30cf3b6a-e5d4-11e4-9237-3a90d40c8f90.png)
![3](https://cloud.githubusercontent.com/assets/12006295/7215192/30d13be0-e5d4-11e4-8499-406bcd3a672a.png)
![4](https://cloud.githubusercontent.com/assets/12006295/7215194/30d17506-e5d4-11e4-8b02-b4e0de2548fa.png)

There is also a bug which already was in previous versions. AFAIK, this icons must be much smaller:
![add](https://cloud.githubusercontent.com/assets/12006295/7215198/4924894a-e5d4-11e4-947a-d391c31427f2.png)
![add2](https://cloud.githubusercontent.com/assets/12006295/7215199/4925c350-e5d4-11e4-8638-aed4b10547af.png)

Arch Linux, nitrux-icon-theme from AUR.

**Comment by UriHerrera** [comment]
The tars were mixed when I uploaded them. I too installed the package on Antergos from the AUR and it installs the wrong icons. If the maintainer hasn't updated the PKGBUILD download them from our site.

**Comment by solbjorn** [comment]
Yes, PKGBUILD was updated (although maintainer hasn't changed pkgel, so i missed this update), and the problem with symbolic icons has gone. But the problem №2 with system monitor and archive manager icons is still (and was in 3.4).

**Comment by UriHerrera** [comment]
I have fixed that too version 3.5.1 (haven't uploaded the TAR to the site yet).
