### ISSUE TITLE
Ubuntu 15.04 creates sizing (and other) problems

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#63]
One typical example is the green **exec** icon (used for most processes, etc.) displayed in much larger size; the other 2 are **nautilus** and **gnome-weather** icons, although many others like chrome, compiz, dropbox, gnome-session, thunderbird, etc. are OK.
![screenshot from 2015-04-27 19 09 09]
(https://cloud.githubusercontent.com/assets/6375934/7351969/42ef468e-ed11-11e4-968e-0970dd3d7c45.png)
![screenshot from 2015-04-27 19 08 34]
(https://cloud.githubusercontent.com/assets/6375934/7351976/51374b10-ed11-11e4-9796-6cf6a291544d.png)

There's also a minor problem: fully charged battery is displayed with "missing icon" symbol, which wasn't the case before the upgrade.

![screenshot from 2015-04-27 19 10 40](https://cloud.githubusercontent.com/assets/6375934/7351981/623eea4e-ed11-11e4-93a9-5d35c07e4530.png)

**Comment by UriHerrera** [comment]
1) Remove the following folders:
- mimetypes/
 - 16/
 - 22/
 - 24/
 - 32/

Replace:

`[mimetypes/48]`
[...]
*`MinSize=48`*
[...]

with

`[mimetypes/48]`
[...]
*`MinSize=16`*
[...]

And remove the deleted directories from the index.theme file.

2) Replace:

`[apps/48]`
[...]
*`MinSize=48`*
[...]

with

`[apps/48]`
[...]
*`MinSize=16`*
[...]


3) If you're using Unity remove the battery-x-y-symbolic icons from `status/symbolic`. Unity for some odd reason doesn't use the regular icons for the battery indicator like it does for every other indicator and it uses the symbolic icons. Even though the icons are not missing either.

**Comment by Sadi58** [comment]
Thank you very much! This solved (almost) all the problems.
BTW I had to change the size in the entry for /tools/synaptic also to 16, otherwise the package status icons were too big.
I only have one minor outstanding issue though:
Another "missing icon" => Synaptic / Mark All Upgrades

**Comment by UriHerrera** [comment]
I've made these fixes to version 3.5.1.

===

The icon in the Ubuntu Desktop Information area in Ubuntu Tweak is the distro logo which is in `places/48` I've changed the values for these too.
