### ISSUE TITLE
[Linux] Is it possible to combine light and dark icon themes as in gtk themes? Gnome

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#64]
It seems not there's a new trend at least in Gnome to allow individual apps to choose a light or dark gtk theme, but this poses problems like almost invisible icons on the toolbar.
As a result, I've deleted those files providing dark options in my gtk theme, which is better now.
But I was just wondering if it is at all possible to use a similar system in the icon theme, i.e. providing both light and dark versions and leaving it to individual apps to choose which version to use.
(Maybe Gnome people and/or developers of such apps like Gnome Image Viewer haven't thought of that ;-)

**Comment by UriHerrera** [comment]
it is possible with the GTK theme providing specific color classes for each app thus different apps can have icons colored differently like the Paper GTK theme does for the headerbars.

**Comment by Sadi58** [comment]
Do you mean this is nothing to do with icon themes, it's all about gtk theming?
I thought maybe this required adding Nitrux-Dark icons to corresponding Nitrux sub-folders by only changing their names from xyz.ext to xyz-dark.ext as in the image files used in gtk-3.0 assets sub-folder...

**Comment by UriHerrera** [comment]
It's about the gtk theming yeah.

**Comment by Sadi58** [comment]
OK, thanks...
