### ISSUE TITLE
[Linux] Wireless indicator not displaying correct icons

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#65]
Probably this is because app developers made some changes again.
After upgrading to Ubuntu 15.04 (GTK 3.14) I've begun seeing what looks like the Gnome default (hicolor?) icon during the process of connecting to wireless network, that color animated icon with two green dots, etc...

**Comment by UriHerrera** [comment]
Can you add a screenshot?

**Comment by Sadi58** [comment]
Yes, exactly, it was that old gnome icon. I got rid of it by adding ubuntu-mono-light before hicolor for "Inherits". But somehow I can't reproduce it now, which is strange. Maybe something strange happened at the time, maybe we can consider this issue closed then, sorry :\)
