### ISSUE TITLE
[Linux] non-monocolor "battery-full-charged-symbolic" status icon

### ISSUE THREAD

**Issue by Sadi58** [NitruxSA/nitrux-icons#71]
I'm not sure if this is intentional but I see a green battery image (indicating fully charged battery status) among all other monocolor icons in my systray, and after every upgrade I have to do the following:

```
mv "~/.icons/Nitrux/status/symbolic/battery-full-charged-symbolic.svg" "~/.icons/Nitrux/status/symbolic/battery-full-charged-symbolic.svg.old"
ln -s "~/.icons/Nitrux/status/22/battery_full.svg" "~/.icons/Nitrux/status/symbolic/battery-full-charged-symbolic.svg"
```

**Comment by UriHerrera** [comment]
Yes and that's Unity's fault. I added a note to the `index.theme` ever since I added the battery symbolic icons.

`#	If used in Ubuntu and Unity remove all battery-x-y-symbolic files in status/symbolic.`
` #	If used in Gnome Shell, Cinnamon, Mate, XFCE, LXDE, etc. don't remove any file.`
