### ISSUE TITLE
Otter Browser.

### ISSUE THREAD

**Issue by xandcg** [NitruxSA/nitrux-icons#72]
Dear Uri Herrera,

When the time allow please add a icon for the Otter Browser. It is in development but very functional already.

Thanks!

"Otter Browser aims to recreate the best aspects of the classic Opera (12.x) UI using Qt5."
http://otter-browser.org/

[Desktop Entry]
Name=Otter Browser
![otter-browser](https://cloud.githubusercontent.com/assets/6910384/8477972/9f717aa0-20a4-11e5-8e58-6528c772d7fc.png)
Icon=otter-browser
Type=Application
Categories=Network;WebBrowser;
Exec=otter-browser %u
Terminal=false
StartupNotify=false
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;

**Comment by UriHerrera** [comment]
Added to version 3.5.3
